spring:
  datasource:
    url:  jdbc:postgres://ofksahuisrbbjr:1914ab8cf8d1417bf3ca0fb198647311561e60d879f8712f3b3cd8cf84cd0722@ec2-54-247-123-231.eu-west-1.compute.amazonaws.com:5432/d2bi51lug1jjad
    username: ofksahuisrbbjr
    password: 1914ab8cf8d1417bf3ca0fb198647311561e60d879f8712f3b3cd8cf84cd0722
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true


  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false

ldap:
  url: ldaps://ldap.myatos.net:636/
  user: uid=es-Lsis_DAS1_auth,ou=functionalaccounts,dc=atosorigin,dc=com
  pass: 1JAifA!m78F
  employee_ou: ou=people,dc=atosorigin,dc=com
  
server:
    port: 5000